#!/bin/bash

# Simple bash script to setup slcli

[ -f ~/.softlayer ] && rm -f ~/.softlayer

echo "Please enter SoftLayer username and apikey in order to use slcli."

echo -n "Enter SoftLayer user name [ENTER]: "
read slusername
echo -n "Enter Softlayer apikey and press [ENTER]: "
read slapikey

cat >> ~/.softlayer << EOF
[softlayer]
username=${slusername}
api_key=${slapikey}
EOF

echo "Current slcli config is:"
slcli config show
